services:
  - type: web
    name: qatar-foundation-admin
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r ../requirements.txt && pip install gunicorn
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
